### ISSUE TITLE
2-1 # 2

### ISSUE THREAD

**Issue by jmbeach** [mdgriest/Studying-for-CS-403-Exam-02#1]
You answered that make-rat needs only 1 or 2 cases to simplify its answer. Could the answer actually be 4?
Aka it needs to check if the for the following cases

|numerator|denomenator
|---|---
|int|int
|int|real
|real|int
|real|real

Would it not have to handle those differently? 

I am confused by your answer to question 1 as well because you don't test on any reals.

**Comment by mdgriest** [comment]
You are correct that there are four possible cases (although I am going to assume that everywhere you said "real" you meant "rational," since the question asked us to handle integers and rationals).

However, both pair-make-rat and int-make-rat (which accomplish the same thing, just using different predicates) construct a rational number from a given numerator and a given denominator by simply checking for each whether it is an integer or a rational number (see pair-to-rat and int-to-rat).

The reason we say one or two cases is that if you look only at the int-make-rat or pair-make-rat function, they each handle only one case, but if you consider the helper functions they use, each handles two cases (pair?/else, integer?/else).

Hope this clears things up.

**Comment by jmbeach** [comment]
Sorry, I meant rational

**Comment by mdgriest** [comment]
No worries. With that in mind, did my explanation clear things up for you?

**Comment by jmbeach** [comment]
Digesting it now

**Comment by jmbeach** [comment]
I definitely had an underlying problem in creating this issue in that I confused real and rational in my head and was wondering why you didn't create cases such as
```scheme
(make-rat (real 7) (real 3))
```
Sorry for the confusion. There's no issue with your solution.

**Comment by jmbeach** [comment]
And thanks for sharing this repo by the way

**Comment by mdgriest** [comment]
Glad we got that figured out! And no problem. I have learned so much while making it and hope it can be a useful tool for at least a few folks heading in to this next exam.
